@extends('spa-views.master')
<!-- Inspiro Slider -->

@section('header-styles')

@endsection
@section('content')
  <div class="container">
  <p align="CENTER"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: x-large;"><strong>Terms Of Use</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Your use of the Portal is governed by the following terms and conditions ("Terms of Use"), as well as the&nbsp; Salt Capital Equity Group Privacy Policy,&nbsp;Indemnification Terms&nbsp;below&nbsp;and other operating rules, minimum qualifications and cautions posted throughout the Portal or presented to you individually during the course of your use of the Portal (collectively, the "Terms"). The Terms govern your use of the Portal and Salt Capital Equity Group reserves the right to update or replace the Terms any time without notice and you are advised to review the Terms for any changes when you visit the Portal even if you have not received a notification of changes as you are bound by them even if you have not reviewed them. Your viewing and use of the Portal after such change constitutes your acceptance of the Terms and any changes to such terms. If at any time you do not want to be bound by the Terms you should logout, exit and cease using the Portal immediately.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Intended Use of Portal</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Salt Capital Equity Group provides a marketplace that enables individuals and firms to seek investment opportunities.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Salt Capital Equity Group is not a broker-dealer or placement agent. At no time does Salt Capital Equity Group offer, broker, advise, purchase, sell or otherwise transact in securities regulated by the SEC or federal or state law. Salt Capital Equity Group does not accept, hold or transfer cash or securities. Salt Capital Equity Group does not guarantee that a Company seeking investment will achieve any level of success or that any proposed offering will qualify under applicable federal and state securities laws.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Salt Capital Equity Group is not a personal financial advisor. Salt Capital Equity Group, whether through the Portal or otherwise, does not provide personal financial advice, loans or credit, banking, consumer credit ratings, credit decisions, financial products, brokerage accounts, insurance, tax advice, legal advice, or financial or legal services of any kind. Even if featured on the Portal, unless expressly stated otherwise, Salt Capital Equity Group does not provide endorsement to or for any advisor/Company seeking capital or investment opportunity.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Salt Capital Equity Group does not guarantee any results to anyone. All users of the Portal are responsible for making their own decisions to use the Portal and for any activity taken on the Portal, including without limitation registering, posting information about their Company and any proposed financing, reserving an investment, making an investment or otherwise.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>User Registration</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">You may browse the Portal without being a registered user, however, certain features are only accessible to registered users. &nbsp;If you are accepting the Terms on behalf of an organization or entity, rather than in an individual capacity, you represent and warrant that you are authorized to accept the Terms on that organization or entity&rsquo;s behalf and bind them to these Terms (in which case, the references to "you" and "your" in these Terms, except for in this sentence, refer to that organization or entity).</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Only real persons at or above the age of 18 may register for an account and use the Portal. Registering for an account on the Portal creates no commitment or obligation on the registered user to make any investment or seek any investment. All information you provide to the Portal must be truthful, accurate and complete in all material respects. Our registration process may use third-party validation technology, including those provided by third-party social media sites, to attempt to confirm your qualification to use the Portal. Salt Capital Equity Group may reject any application to register an individual or an organization or entity for failure to achieve validation through available methods or otherwise meet salt capital equity group&rsquo;s registration requirements.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Your registration and the use of any third-party site is subject to the terms and conditions and policies of such sites and Salt Capital Equity Group is not responsible or liable for any harm resulting from the use or misuse of those sites, including when such harm could or does affect your account on this Portal or use of the Portal. If you wish to disconnect your Portal account from your validation account, please following instructions provided on the Portal or contact our customer service.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Registered Account Obligations</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">The named registered user of an account is the only person that may use the account and it may not be transferred to anyone else. If you are a control person on a Company page, you may transfer responsibility for the page to another individual by contacting customer service. If you represent a firm considering or managing an investment on the Portal or providing advisory services, your replacement representative must register for his/her own account and establish any links from that account that may be available on the site to the firm.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">You are responsible for maintaining the confidentiality of your username and password and to periodically change your password to maintain security. If you have concerns that your user name or password may have been compromised and suspect that unauthorized access to your account or the Portal has occurred, you must immediately contact Salt Capital Equity Group&rsquo;s management team through a secure method (which may not be through your Portal account).</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Content Use Limitations</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Your use of the Portal and its videos, webinars, images, infographics, alerts, text, articles, assessments, checklists, forms, ratings, design, data, source code, analytics, photos, software, trademarks, copyrights, and other information ("Content") may only be used for the lawful and intended purposes expressly authorized by salt capital equity group. If you access this Portal from outside the United States, you are solely responsible for ensuring compliance with the laws of your specific jurisdiction, as well as any restrictions that you may be subject to by a department of the United States government. Any misuse or unauthorized use of the Portal and its Content, or other violations of the Terms may violate Applicable Law (see below), including without limitation SEC regulations and applicable state securities laws, copyright laws (including the Digital Millennium Copyright Act), trademark laws, the laws of privacy, laws of publicity, identity theft and communications statutes and regulations, in which case Salt Capital Equity Group is authorized to terminate your account and access to the Portal at any time and without notice and report you to the appropriate authorities and other interested parties, such as a claimed intellectual property owner. See&nbsp;our Privacy Policy for more information.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Even if such Content or activity does not violate Applicable Law, you are prohibited from posting or transmitting any material on or through the Portal that, in Salt Capital Equity Group&rsquo;s sole opinion, is or could be offensive, fraudulent, unlawful, threatening, disingenuous, libelous, defamatory, obscene, scandalous, inflammatory, pornographic or profane, constitutes anti-competitive collaboration or antitrust violations, or any material that could constitute or encourage conduct that would be considered a criminal offense, give rise to civil liability, or otherwise violate any law. Salt Capital Equity Group will fully cooperate with any law enforcement authorities or court order requesting or directing Salt Capital Equity Group to disclose the identity of anyone posting any such information or materials on the Portal.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">By posting Content on the Portal, you represent and warrant that you have all necessary rights to make the Content available on the Portal and acknowledge that all postings on the Portal are not confidential and are available for public viewing.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Prospective Investor Accounts</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Any person or entity that is considering making or makes a reservation of investment with a Company that posts its fundraising plans on the Portal, or, after the fundraising plan becomes a qualified offering, makes an investment, does so at his or her own risk. All investment carries risk that you may lose some or all of your investment. No Content on the Portal is a replacement for performing your own due diligence, exercising good judgment and seeking financial, investment, tax or legal advice from qualified and licensed professionals with knowledge of your personal circumstances. Any registered financial, legal or tax representatives or firm working for or with Salt Capital Equity Group or communicating with you or users in general through the Portal are not your personal advisors and do not have knowledge about your personal circumstances and anything they post is for informational purposes only and may not be accurate to your situation and you agree that you shall not rely on Content on the Portal in making personal decisions about an investment or the potential legal, tax or financial consequences of such investment. You are encouraged to seek personal professional advice from qualified and licensed professionals.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">You are solely responsible for your investment decisions. While you may be asked about your identity, individual financial circumstance and investment experience and sophistication during your engagement with the Portal, Salt Capital Equity Group and its advisors and vendors are not responsible to verify the veracity of the information that you provide, even if you certify to its truth or undergo a suitability review. Whether you are an&nbsp;"Accredited Investor", as such is defined under securities law, or a non-accredited investor, or an institutional investor, Salt Capital Equity Group and the Companies seeking investment are relying on your representations with respect to your investment experience, your financial status and your eligibility to invest. You may, further, be held personally liable for your fraud, negligence and other bad acts that may result from any false representations you make.</span></span></p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Company Offerings</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">By virtue of posting Content, Company provides Salt Capital Equity Group and its affiliates a perpetual, irrevocable, non-exclusive license to the Content and must accept, read and understand all policies, procedures, directions and communications from salt capital equity group. No such individual may be an individual who is prohibited from making securities offerings in the United States or country of residence. The registered individuals and the Company are solely responsible for the Content that they post on the Portal, including any changes to the Content made by its employees and advisors. Each registered individual must disclose their affiliation with and interests in the Company in any Content, post or rating they make on the Portal with respect to their Company and offering, including pages outside the Company page. All Content posted on the Portal must be truthful, accurate and complete in all material respects. Salt Capital Equity Group is not obligated to pre-screen, police, edit or monitor Content posted to the site by users. If any Content is found to be unlawful or fraudulent, the Content and the entire Company page may be removed by Salt Capital Equity Group without notice. The Content may not be reposted until it is corrected. If it is believed to be uncorrectable by Salt Capital Equity Group or its advisors, the registered individuals and the Company may be banned from the Portal.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Each Company and registered individual associated with and posting for the Company is solely responsible for the Content such Company posts on the Portal and, by registering with the Portal and posting Content on the Portal represents and warrants that: (i) he/she/it has and will comply with all applicable laws, regulations, rules, ordinances, judgments, decrees, injunctions, arbitration awards or order of any governmental agency, authority and regulatory body or anybody duly authorized to exercise any administrative, judicial, executive, legislative, police, regulatory or taxing authority power or authority ("Applicable Law"); and (ii) such Content does not contain any untrue statement of a material fact or omit to state a material fact required to be stated or necessary to make such statements not misleading in light of the circumstances under which they are made. The Company, further, is responsible for and shall take reasonable steps to determine the suitability of any prospective investor.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Portal Fees and Payment Terms</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Use of the Portal may be subject to certain fees or charges (collectively the "Fees"). Salt Capital Equity Group will invoice your business for fees due using the contact information you have provided to Salt Capital Equity Group. Prompt payment of fees is required to maintain your Company's live listing on the Portal. All Fees are non-refundable. Salt Capital Equity Group will use commercially reasonable efforts to provide you notice in the event the Fees change.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Advisor Accounts</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Individuals registering as or acting as advisors, analysts or other persons of knowledge or who are such advisors and analysts by trade are required to disclose their licenses, ownership positions and relevant affiliations, including whether a Company is a client, in all interactions with the Portal and with other users of the Portal. Advisors and analysts are solely responsible for the Content they post and any advice or analysis they provide to their client companies or to users of the Portal. Salt Capital Equity Group accepts no responsibility or liability for Content posted by third parties.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Investing Is at Your Own Risk</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Content is provided for educational purposes only and shall not be construed as professional advice. Salt Capital Equity Group is not responsible for pre-screening, policing, editing or monitoring Content posted to the site by users. Because Content only provides general coverage of the subject area without considering your individual financial situation or complexities in the law that might apply to you, before acting on any Content you should consult with a competent professional who can advise you about your specific financial objectives. Any action you take on Content or because of using this website is at your own risk.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">You are solely responsible for using your own judgment in using the Portal, including deciding which financial professional to hire and what products and services you may use and purchase. Salt Capital Equity Group is not responsible for the conduct of any third party and shall not be liable to any damages or costs of any type arising out of or in any way connected with your use of such services and products.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">You may lose all the money you invest in a company on the Portal. If you cannot afford to lose all your investment, you should not invest.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Termination of Account</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Salt Capital Equity Group may suspend or terminate your account and your ability to use the Portal at any time for any lawful reason and Salt Capital Equity Group accepts no liability for any harm that may be caused, directly or indirectly, by such suspension or termination, including without limitation loss of the opportunity to gain investors, complete a fundraising or any fees or gains you could have gained.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Indicate Interest</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">If available (using Reg. A+) you may be able to make an "Indicate Interest" indication on a project which involves no obligation or commitment of any kind. No money or other consideration is being solicited or accepted. Offers to buy securities or pay part of the purchase price cannot be received for any investment in a company until an offering document filed by the applicable company is qualified by the SEC for that investment and through a registered entity. You may withdraw your reservation of investment at any time until a qualified offer of the sale of securities is made and accepted after the SEC offering qualification date. While you keep a reservation, you will be notified if a filing with the SEC is made for a company that you reserved an investment possibility in, when it is amended and when it is qualified. If a test_the_waters or final offering statement is filed with the SEC, it will be made available to you and you are encouraged to read the offering in full as it will provide you with more detailed information about the company, the terms and conditions of any potential offering and the risk, uncertainties and timing associated with any potential offering.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Use of the Portal and Content</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">You agree that the Content cannot be copied, reproduced, distributed, republished, displayed, posted, or transmitted in any form or by any means without the express advance&nbsp;written consent of an officer of Salt Capital Equity Group or the applicable licensor. You may not modify, participate in the sale or transfer of, or create any derivative works based on any part of all of the Content. Using Content, including by linking, framing, or mirroring for any purpose, is prohibited without the express advance written consent of an officer of salt capital equity group.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Opinions expressed, or material appearing, on this website are not shared or endorsed by Salt Capital Equity Group and Salt Capital Equity Group should not be regarded as the publisher of such opinions or material. Please be aware that Salt Capital Equity Group is not responsible for the privacy practices, or Content, of third parties. Evaluate the security and trustworthiness of any other site connected to the Portal and any advisor you access through this Portal before disclosing any personal information to them. Salt Capital Equity Group will not accept any responsibility for any loss or damage in whatever manner, howsoever caused, resulting from your interactions with third parties.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">All licensors of Content warrant to Salt Capital Equity Group that they have full rights to share the Content on the Portal and with Salt Capital Equity Group and any other user of the Portal. Companies seeking investment are solely responsible for the Content that they post and the responses they provide. Salt Capital Equity Group may, but is not required to, suspend or terminate any user and remove their Content if Salt Capital Equity Group has reasonable grounds to believe that the registration and any Content is untrue, inaccurate, not current or incomplete. Salt Capital Equity Group does not validate the information for accuracy or ownership rights or whether it is current. Salt Capital Equity Group expressly disclaims any responsibility and all warranties of accuracy, truthfulness and completeness of the information posted.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Availability of Portal</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Salt Capital Equity Group does not warrant the Portal, its Content or any services provided or offered on the Portal or any content or services you obtain through your use of the Portal (such as hiring an advisor or making an investment decision) will be uninterrupted, timely, or virus or error free. Salt Capital Equity Group and its advisors do not guarantee that any financial, legal, tax or other professional you may require will be available or meet your expectations or be able to address all issues you may raise or require. You agree not to modify, damage, disrupt, disable, overburden, impair, alter or interfere with the use, features, functions, operation, security or maintenance of the Portal or the rights or use and enjoyment of the Portal by any other person or entity in any manner.&nbsp;By using the Portal you release salt capital equity group, its employees, contractors, advisors, vendors, agents, and affiliates against any and all loss, damage, and claims, in whatever manner, howsoever caused arising from or related to your use of the Portal and any advisor you retain or rely on or any investment decision you may make.</span></span></p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Disclaimers, Exclusions, and Limitations of Liability</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">THE PORTAL AND ITS CONTENT ARE PROVIDED ON AN "AS IS" AND &ldquo;AS AVAILABLE&rdquo; BASIS AND USE OF THE PORTAL IN ANY MANNER IS SOLELY AT YOUR OWN RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, Salt Capital Equity Group DOES NOT GUARANTEE, AND EXPRESSLY EXCLUDES ALL REPRESENTATIONS AND WARRANTIES, EXPRESS OR IMPLIED, RELATING TO THE PORTAL AND ITS CONTENT AND PROFESSIONAL SERVICES, WHETHER PROVIDED BY salt capital equity group, OUR AFFILIATES, OUR CUSTOMERS, COMPANIES SEEKING INVESTMENT, ADVISORS, INVESTORS OR ANY OTHER THIRD PARTY, INCLUDING IN RELATION TO ANY INACCURACIES, ERRORS, OR OMISSIONS IN THE PORTAL, ITS CONTENT, FINANCIAL ADVICE, AND/OR MARKETING MATERIALS.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">SHALL HAVE NO LIABILITY FOR DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR USE, DELAY, OR UNAVAILABILITY OF THE PORTAL AND ITS CONTENT, INCLUDING LOSS OF MONEY, INABILITY TO CONCLUDE AN INVESTMENT, SUSPENSION OR TERMINATION OF YOUR ACCOUNT AND FOR ANY DAMAGE CAUSED TO YOUR COMPUTER, COMPUTER SOFTWARE, SYSTEMS, PROGRAMS, AND THE DATA THEREON. UNDER NO CIRCUMSTANCES WILL Salt Capital Equity Group OR ITS AFFILIATES, ADVISORS AND VENDORS BE LIABLE FOR ANY DAMAGES, INCLUDING GENERAL, SPECIAL, PUNITIVE, DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR ANY OTHER DAMAGES (INCLUDING, WITHOUT LIMITATION, LOST PROFITS OR BUSINESS INTERRUPTION) OF ANY KIND WHETHER IN AN ACTION IN CONTRACT, TORT, OR NEGLIGENCE ARISING OR RELATING IN ANY WAY TO THE USE OR INABILITY TO USE BY ANY PARTY OF THE PORTAL, THE CONTENT, OR ANY THIRD-PARTY WEBSITE THAT IS LINKED TO BY THE PORTAL, OR IN CONNECTION WITH ANY FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMPUTER VIRUS, OR LINE OR SYSTEM FAILURE, EVEN IF&nbsp;IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, LOSSES, OR EXPENSES.</span></span></p>
  <p><a name="_GoBack"></a><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">SALT CAPITAL EQUITY GROUP SHALL NOT BE LIABLE FOR ANY DEFAMATORY, OFFENSIVE OR ILLEGAL CONDUCT OF ANY PORTAL USER. YOUR&nbsp;SOLE REMEDY&nbsp;FOR DISSATISFACTION WITH THE PORTAL IS TO STOP USING THE PORTAL. IF USING MATERIALS FROM THE PORTAL RESULTS IN THE NEED FOR SERVICING, REPAIR OR CORRECTION OF EQUIPMENT OR DATA, YOU ASSUME ANY COSTS; AND, IF ANY OR ALL THE FOREGOING PARAGRAPHS ARE FOUND TO BE INVALID, IN WHOLE OR IN PART, YOU AGREE THAT OUR TOTAL LIABILITY FOR ALL DAMAGES, LOSSES, OR CAUSES OF ACTION OF ANY KIND OR NATURE SHALL BE LIMITED TO COMPENSATORY DAMAGES AND LIMITED TO THE GREATEST EXTENT PERMITTED BY APPLICABLE LAW.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Indemnification</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">By registering with the Portal, Company representatives individually and on behalf of their Company hereby agree to indemnify, defend and hold salt capital equity group, shareholders, investors, officers, directors, employees, consultants, advisors, service providers, suppliers, vendors, advertisers, agents ("Related Parties") and its affiliates and their Related Parties in accordance with these Indemnification Terms. The Indemnification Terms constitute Terms hereunder. You are cautioned and advised to review the Indemnification Terms in full.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Choice of Law, Time Limit and Arbitration</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">The laws of the State of&nbsp;Louisiana govern these Terms. Salt Capital Equity Group makes no representation that the Portal is operated in compliance with the laws of any nation but the United States. If you are located outside the United States, you view this website and access the Portal at your own risk and initiative.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">This Portal and the Content posted on it or made available through it shall not constitute an offer or solicitation and may not be treated as an offer or solicitation: (i) in any jurisdiction where such an offer or solicitation is against the law; (ii) to anyone to whom it is unlawful to make such an offer or solicitation; or (iii) if the person making the offer or solicitation is not qualified to do so. Any securities that may be offered on the Portal can only be marketed in certain jurisdictions. You acknowledge and agree that it is solely your responsibility to be aware of the applicable laws and regulations of your country of residence.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">By accessing the Portal you agree that in the event of any dispute between you and Salt Capital Equity Group and its Related Parties and its affiliates and their Related Parties, you will first attempt in good faith to resolve the dispute at least 60 days before instituting any formal proceeding. You must bring all disputes with Salt Capital Equity Group within one year of obtaining knowledge of the cause of action forming the basis of the dispute. You, Salt Capital Equity Group, its affiliates and all Related Parties agree to submit any dispute for binding arbitration. To the full extent allowable by law, you agree that no arbitration proceeding, or other dispute resolution proceeding shall be joined with any other party or decided on a class-action basis.</span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Waiver</strong></span></span></p>
  <p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Failure of Salt Capital Equity Group to insist upon strict performance of any provision of the Terms or the failure of Salt Capital Equity Group to exercise any right or remedy to which it is entitled shall not constitute a waiver thereof and shall not affect the validity of the Terms, or any part, or&nbsp; salt capital equity group's right to enforce each and every provision. If any of the Terms are deemed invalid or unenforceable for any reason (including, but not limited to the exclusions and limitations set out above), then the invalid or unenforceable provision will be severed from the Terms and the remaining Terms will continue to apply.</span></span></p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
</div>
@endsection


@section('footer-scripts')

@endsection
